import './Legal.css';

export default function TermsOfService() {
    return (
        <main className="legal-page">
            <div className="legal-page__header">
                <div className="container">
                    <span className="badge">Legal</span>
                    <h1>Terms of Service</h1>
                    <p className="legal-page__meta">Effective Date: 3/22/26 &nbsp;&middot;&nbsp; Last Updated: 3/22/26</p>
                    <p className="legal-page__intro">
                        These Terms govern your access to and use of Seyona.ai and its related services, operated by Sherpa Technologies LLC ("we," "us," or "our"). By creating an account or using Seyona, you agree to these Terms.
                    </p>
                </div>
            </div>

            <div className="container">
                <div className="legal-page__body">

                    <section className="legal-section">
                        <h2>1. What Seyona Does</h2>
                        <p>Seyona is a SaaS platform that generates FAQ content and structured data (JSON-LD schema markup) and injects it into your website via a script tag. Content is generated using AI and refreshes on a schedule you configure.</p>
                    </section>

                    <section className="legal-section">
                        <h2>2. Eligibility</h2>
                        <p>You must be at least 18 years old and have the authority to enter into these Terms on behalf of yourself or your organization. By using Seyona, you represent that you meet these requirements.</p>
                    </section>

                    <section className="legal-section">
                        <h2>3. Your Account</h2>
                        <p>You are responsible for maintaining the security of your account credentials. You must notify us promptly if you suspect unauthorized access. We are not liable for losses resulting from unauthorized account access caused by your failure to secure your credentials.</p>
                    </section>

                    <section className="legal-section">
                        <h2>4. The Seyona Script</h2>
                        <p>When you install the Seyona script tag on your website, you authorize Seyona to:</p>
                        <ul>
                            <li>Inject AI-generated FAQ content and JSON-LD schema markup into your web pages</li>
                            <li>Read page signals (URL, page title, visible content structure) to generate relevant content</li>
                            <li>Deliver and refresh content on the schedule you configure in your dashboard</li>
                        </ul>
                        <p>You remain responsible for the content that appears on your website, including AI-generated content delivered by Seyona. You should review generated content periodically to ensure it meets your standards.</p>
                    </section>

                    <section className="legal-section">
                        <h2>5. AI-Generated Content</h2>
                        <p>Content generated by Seyona is produced by AI and is provided as-is. We do not guarantee that generated content is:</p>
                        <ul>
                            <li>Accurate, complete, or up to date</li>
                            <li>Free from errors, omissions, or inaccuracies</li>
                            <li>Suitable for regulated industries (medical, legal, financial) without human review</li>
                        </ul>
                        <p>You assume full responsibility for any AI-generated content published on your website. We strongly recommend reviewing generated content before it goes live, particularly for sensitive topics.</p>
                    </section>

                    <section className="legal-section">
                        <h2>6. Acceptable Use</h2>
                        <p>You agree not to use Seyona to:</p>
                        <ul>
                            <li>Generate content that is false, misleading, defamatory, or illegal</li>
                            <li>Violate any applicable laws or regulations</li>
                            <li>Infringe on the intellectual property rights of any third party</li>
                            <li>Attempt to reverse-engineer, scrape, or abuse our platform or APIs</li>
                            <li>Resell or sublicense Seyona without our written consent</li>
                        </ul>
                        <p>We reserve the right to suspend or terminate accounts that violate these terms.</p>
                    </section>

                    <section className="legal-section">
                        <h2>7. Subscription and Billing</h2>
                        <p>Seyona offers paid subscription plans billed monthly. Pricing is listed at seyona.ai and is subject to change with notice. Billing is handled by Stripe. By subscribing, you authorize recurring charges to your payment method.</p>
                        <p><strong>Cancellations:</strong> You may cancel your subscription at any time from your dashboard. Access continues through the end of the current billing period. No partial refunds are issued for unused time.</p>
                        <p><strong>Free Trial:</strong> Where offered, free trials automatically convert to paid subscriptions at the end of the trial period unless cancelled beforehand.</p>
                    </section>

                    <section className="legal-section">
                        <h2>8. Intellectual Property</h2>
                        <p>You retain ownership of your website content and any data you provide to Seyona. We retain ownership of the Seyona platform, script, and underlying technology.</p>
                        <p>AI-generated content produced for your account is yours to use. We do not claim ownership over content generated on your behalf.</p>
                    </section>

                    <section className="legal-section">
                        <h2>9. Uptime and Service Availability</h2>
                        <p>We aim to maintain reliable service but do not guarantee uninterrupted availability. Scheduled maintenance, outages, or third-party infrastructure issues may cause temporary disruptions. We are not liable for losses resulting from service unavailability.</p>
                    </section>

                    <section className="legal-section">
                        <h2>10. Disclaimer of Warranties</h2>
                        <p>Seyona is provided "as is" without warranties of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that Seyona will improve your search rankings, traffic, or any other metric.</p>
                    </section>

                    <section className="legal-section">
                        <h2>11. Limitation of Liability</h2>
                        <p>To the fullest extent permitted by law, Sherpa Technologies LLC shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of Seyona. Our total liability for any claim arising out of these Terms shall not exceed the amount you paid us in the three months preceding the claim.</p>
                    </section>

                    <section className="legal-section">
                        <h2>12. Termination</h2>
                        <p>We may suspend or terminate your account at any time for violations of these Terms or for any other reason with reasonable notice. You may terminate your account at any time by cancelling your subscription and contacting us.</p>
                    </section>

                    <section className="legal-section">
                        <h2>13. Governing Law</h2>
                        <p>These Terms are governed by the laws of the State of Rhode Island, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Rhode Island.</p>
                    </section>

                    <section className="legal-section">
                        <h2>14. Changes to These Terms</h2>
                        <p>We may update these Terms from time to time. We will notify you of material changes via email or in-app notice. Continued use of Seyona after changes take effect constitutes acceptance of the updated Terms.</p>
                    </section>

                    <section className="legal-section">
                        <h2>15. Contact</h2>
                        <p>For questions about these Terms, contact us at: jared@seyona.ai</p>
                    </section>

                </div>
            </div>
        </main>
    );
}
